[2024-12-03T13:36:24.357+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-03T13:36:24.385+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T13:36:24.400+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T13:36:24.401+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-03T13:36:24.427+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_and_store_data> on 2024-12-02 00:00:00+00:00
[2024-12-03T13:36:24.439+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=96) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-03T13:36:24.440+0000] {standard_task_runner.py:72} INFO - Started process 102 to run task
[2024-12-03T13:36:24.441+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'finance_data_generator', 'generate_and_store_data', 'scheduled__2024-12-02T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/finance_data_generator.py', '--cfg-path', '/tmp/tmpdwbtcu9k']
[2024-12-03T13:36:24.442+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask generate_and_store_data
[2024-12-03T13:36:24.508+0000] {task_command.py:467} INFO - Running <TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [running]> on host 025aad38a8b7
[2024-12-03T13:36:24.638+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='finance_data_generator' AIRFLOW_CTX_TASK_ID='generate_and_store_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-02T00:00:00+00:00'
[2024-12-03T13:36:24.640+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-03T13:36:24.641+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-03T13:36:24.641+0000] {logging_mixin.py:190} INFO - Current task name:generate_and_store_data state:running start_date:2024-12-03 13:36:24.386590+00:00
[2024-12-03T13:36:24.641+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator and current dag run status:running
[2024-12-03T13:36:24.642+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-03T13:55:59.362+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-03T13:55:59.390+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T13:55:59.403+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T13:55:59.403+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-03T13:55:59.424+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_and_store_data> on 2024-12-02 00:00:00+00:00
[2024-12-03T13:55:59.433+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=97) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-03T13:55:59.435+0000] {standard_task_runner.py:72} INFO - Started process 102 to run task
[2024-12-03T13:55:59.437+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'finance_data_generator', 'generate_and_store_data', 'scheduled__2024-12-02T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/finance_data_generator.py', '--cfg-path', '/tmp/tmp_kn_83ct']
[2024-12-03T13:55:59.438+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask generate_and_store_data
[2024-12-03T13:55:59.495+0000] {task_command.py:467} INFO - Running <TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [running]> on host b5758e9f13be
[2024-12-03T13:55:59.594+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='finance_data_generator' AIRFLOW_CTX_TASK_ID='generate_and_store_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-02T00:00:00+00:00'
[2024-12-03T13:55:59.596+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-03T13:55:59.597+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-03T13:55:59.597+0000] {logging_mixin.py:190} INFO - Current task name:generate_and_store_data state:running start_date:2024-12-03 13:55:59.390550+00:00
[2024-12-03T13:55:59.598+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator and current dag run status:running
[2024-12-03T13:55:59.598+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-03T13:55:59.694+0000] {logging_mixin.py:190} INFO - Transactions successfully stored in database
[2024-12-03T13:55:59.695+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-03T13:55:59.710+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-03T13:55:59.711+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=finance_data_generator, task_id=generate_and_store_data, run_id=scheduled__2024-12-02T00:00:00+00:00, execution_date=20241202T000000, start_date=20241203T135559, end_date=20241203T135559
[2024-12-03T13:55:59.721+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-03T13:55:59.721+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-03T13:55:59.721+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator queued_at:2024-12-03 13:55:54.012752+00:00
[2024-12-03T13:55:59.722+0000] {logging_mixin.py:190} INFO - Task hostname:b5758e9f13be operator:PythonOperator
[2024-12-03T13:55:59.769+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-03T13:55:59.790+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T13:55:59.792+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-03T14:03:16.689+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-03T14:03:16.712+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T14:03:16.723+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T14:03:16.723+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-03T14:03:16.741+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_and_store_data> on 2024-12-02 00:00:00+00:00
[2024-12-03T14:03:16.751+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=82) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-03T14:03:16.752+0000] {standard_task_runner.py:72} INFO - Started process 85 to run task
[2024-12-03T14:03:16.753+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'finance_data_generator', 'generate_and_store_data', 'scheduled__2024-12-02T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/finance_data_generator.py', '--cfg-path', '/tmp/tmpxlakp23g']
[2024-12-03T14:03:16.754+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask generate_and_store_data
[2024-12-03T14:03:16.815+0000] {task_command.py:467} INFO - Running <TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [running]> on host b9f7a4adc526
[2024-12-03T14:03:16.929+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='finance_data_generator' AIRFLOW_CTX_TASK_ID='generate_and_store_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-02T00:00:00+00:00'
[2024-12-03T14:03:16.930+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-03T14:03:16.930+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-03T14:03:16.931+0000] {logging_mixin.py:190} INFO - Current task name:generate_and_store_data state:running start_date:2024-12-03 14:03:16.713111+00:00
[2024-12-03T14:03:16.931+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator and current dag run status:running
[2024-12-03T14:03:16.931+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-03T14:06:42.538+0000] {logging_mixin.py:190} INFO - Transactions successfully stored in database
[2024-12-03T14:06:42.539+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-03T14:06:42.579+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-03T14:06:42.580+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=finance_data_generator, task_id=generate_and_store_data, run_id=scheduled__2024-12-02T00:00:00+00:00, execution_date=20241202T000000, start_date=20241203T140316, end_date=20241203T140642
[2024-12-03T14:06:42.612+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-03T14:06:42.613+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-03T14:06:42.613+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator queued_at:2024-12-03 14:03:10.694469+00:00
[2024-12-03T14:06:42.613+0000] {logging_mixin.py:190} INFO - Task hostname:b9f7a4adc526 operator:PythonOperator
[2024-12-03T14:06:42.688+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-03T14:06:42.744+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T14:06:42.754+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-03T14:12:36.551+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-03T14:12:36.572+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T14:12:36.583+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T14:12:36.583+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-03T14:12:36.603+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_and_store_data> on 2024-12-02 00:00:00+00:00
[2024-12-03T14:12:36.613+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=84) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-03T14:12:36.614+0000] {standard_task_runner.py:72} INFO - Started process 89 to run task
[2024-12-03T14:12:36.616+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'finance_data_generator', 'generate_and_store_data', 'scheduled__2024-12-02T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/finance_data_generator.py', '--cfg-path', '/tmp/tmpkxdaaca3']
[2024-12-03T14:12:36.617+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask generate_and_store_data
[2024-12-03T14:12:36.683+0000] {task_command.py:467} INFO - Running <TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [running]> on host 013f55368d4e
[2024-12-03T14:12:36.790+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='finance_data_generator' AIRFLOW_CTX_TASK_ID='generate_and_store_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-02T00:00:00+00:00'
[2024-12-03T14:12:36.792+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-03T14:12:36.793+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-03T14:12:36.793+0000] {logging_mixin.py:190} INFO - Current task name:generate_and_store_data state:running start_date:2024-12-03 14:12:36.573044+00:00
[2024-12-03T14:12:36.794+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator and current dag run status:running
[2024-12-03T14:12:36.794+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-03T14:13:46.861+0000] {logging_mixin.py:190} INFO - Transactions successfully stored in database
[2024-12-03T14:13:46.862+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-03T14:13:46.892+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-03T14:13:46.892+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=finance_data_generator, task_id=generate_and_store_data, run_id=scheduled__2024-12-02T00:00:00+00:00, execution_date=20241202T000000, start_date=20241203T141236, end_date=20241203T141346
[2024-12-03T14:13:46.926+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-03T14:13:46.927+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-03T14:13:46.927+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator queued_at:2024-12-03 14:12:31.364399+00:00
[2024-12-03T14:13:46.928+0000] {logging_mixin.py:190} INFO - Task hostname:013f55368d4e operator:PythonOperator
[2024-12-03T14:13:46.962+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-03T14:13:47.016+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T14:13:47.023+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-03T14:19:47.247+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-03T14:19:47.266+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T14:19:47.275+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T14:19:47.275+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-03T14:19:47.289+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_and_store_data> on 2024-12-02 00:00:00+00:00
[2024-12-03T14:19:47.296+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=88) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-03T14:19:47.297+0000] {standard_task_runner.py:72} INFO - Started process 93 to run task
[2024-12-03T14:19:47.299+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'finance_data_generator', 'generate_and_store_data', 'scheduled__2024-12-02T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/finance_data_generator.py', '--cfg-path', '/tmp/tmpib__sv8_']
[2024-12-03T14:19:47.300+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask generate_and_store_data
[2024-12-03T14:19:47.371+0000] {task_command.py:467} INFO - Running <TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [running]> on host c75265b578f3
[2024-12-03T14:19:47.471+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='finance_data_generator' AIRFLOW_CTX_TASK_ID='generate_and_store_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-02T00:00:00+00:00'
[2024-12-03T14:19:47.472+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-03T14:19:47.472+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-03T14:19:47.473+0000] {logging_mixin.py:190} INFO - Current task name:generate_and_store_data state:running start_date:2024-12-03 14:19:47.266396+00:00
[2024-12-03T14:19:47.473+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator and current dag run status:running
[2024-12-03T14:19:47.473+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-03T14:19:47.552+0000] {logging_mixin.py:190} INFO - Transactions successfully stored in database
[2024-12-03T14:19:47.552+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-03T14:19:47.564+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-03T14:19:47.565+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=finance_data_generator, task_id=generate_and_store_data, run_id=scheduled__2024-12-02T00:00:00+00:00, execution_date=20241202T000000, start_date=20241203T141947, end_date=20241203T141947
[2024-12-03T14:19:47.576+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-03T14:19:47.576+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-03T14:19:47.576+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator queued_at:2024-12-03 14:19:42.238315+00:00
[2024-12-03T14:19:47.577+0000] {logging_mixin.py:190} INFO - Task hostname:c75265b578f3 operator:PythonOperator
[2024-12-03T14:19:47.592+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-03T14:19:47.614+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T14:19:47.616+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-03T14:38:53.333+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-03T14:38:53.355+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T14:38:53.364+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T14:38:53.364+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-03T14:38:53.381+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_and_store_data> on 2024-12-02 00:00:00+00:00
[2024-12-03T14:38:53.392+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=96) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-03T14:38:53.393+0000] {standard_task_runner.py:72} INFO - Started process 102 to run task
[2024-12-03T14:38:53.395+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'finance_data_generator', 'generate_and_store_data', 'scheduled__2024-12-02T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/finance_data_generator.py', '--cfg-path', '/tmp/tmpwc26fnq_']
[2024-12-03T14:38:53.396+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask generate_and_store_data
[2024-12-03T14:38:53.469+0000] {task_command.py:467} INFO - Running <TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [running]> on host d2d4ba9c33a8
[2024-12-03T14:38:53.592+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='finance_data_generator' AIRFLOW_CTX_TASK_ID='generate_and_store_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-02T00:00:00+00:00'
[2024-12-03T14:38:53.593+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-03T14:38:53.593+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-03T14:38:53.594+0000] {logging_mixin.py:190} INFO - Current task name:generate_and_store_data state:running start_date:2024-12-03 14:38:53.356090+00:00
[2024-12-03T14:38:53.594+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator and current dag run status:running
[2024-12-03T14:38:53.594+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-03T14:40:16.038+0000] {logging_mixin.py:190} INFO - Transactions successfully stored in database
[2024-12-03T14:40:16.039+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-03T14:40:16.083+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-03T14:40:16.084+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=finance_data_generator, task_id=generate_and_store_data, run_id=scheduled__2024-12-02T00:00:00+00:00, execution_date=20241202T000000, start_date=20241203T143853, end_date=20241203T144016
[2024-12-03T14:40:16.113+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-03T14:40:16.114+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-03T14:40:16.114+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator queued_at:2024-12-03 14:38:47.902714+00:00
[2024-12-03T14:40:16.115+0000] {logging_mixin.py:190} INFO - Task hostname:d2d4ba9c33a8 operator:PythonOperator
[2024-12-03T14:40:16.168+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-03T14:40:16.201+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T14:40:16.212+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-03T14:48:14.084+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-03T14:48:14.110+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T14:48:14.121+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T14:48:14.122+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-03T14:48:14.150+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_and_store_data> on 2024-12-02 00:00:00+00:00
[2024-12-03T14:48:14.157+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=81) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-03T14:48:14.158+0000] {standard_task_runner.py:72} INFO - Started process 85 to run task
[2024-12-03T14:48:14.160+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'finance_data_generator', 'generate_and_store_data', 'scheduled__2024-12-02T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/finance_data_generator.py', '--cfg-path', '/tmp/tmpvw8fh4ib']
[2024-12-03T14:48:14.161+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask generate_and_store_data
[2024-12-03T14:48:14.223+0000] {task_command.py:467} INFO - Running <TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [running]> on host 0790f72a2075
[2024-12-03T14:48:14.353+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='finance_data_generator' AIRFLOW_CTX_TASK_ID='generate_and_store_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-02T00:00:00+00:00'
[2024-12-03T14:48:14.354+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-03T14:48:14.354+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-03T14:48:14.355+0000] {logging_mixin.py:190} INFO - Current task name:generate_and_store_data state:running start_date:2024-12-03 14:48:14.111371+00:00
[2024-12-03T14:48:14.355+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator and current dag run status:running
[2024-12-03T14:48:14.356+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-03T14:48:14.451+0000] {logging_mixin.py:190} INFO - Transactions successfully stored in database
[2024-12-03T14:48:14.452+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-03T14:48:14.469+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-03T14:48:14.469+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=finance_data_generator, task_id=generate_and_store_data, run_id=scheduled__2024-12-02T00:00:00+00:00, execution_date=20241202T000000, start_date=20241203T144814, end_date=20241203T144814
[2024-12-03T14:48:14.484+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-03T14:48:14.485+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-03T14:48:14.485+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator queued_at:2024-12-03 14:48:08.973829+00:00
[2024-12-03T14:48:14.485+0000] {logging_mixin.py:190} INFO - Task hostname:0790f72a2075 operator:PythonOperator
[2024-12-03T14:48:14.534+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-03T14:48:14.557+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T14:48:14.559+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-03T15:04:44.274+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-03T15:04:44.298+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T15:04:44.311+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T15:04:44.311+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-03T15:04:44.330+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_and_store_data> on 2024-12-02 00:00:00+00:00
[2024-12-03T15:04:44.343+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=75) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-03T15:04:44.344+0000] {standard_task_runner.py:72} INFO - Started process 81 to run task
[2024-12-03T15:04:44.346+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'finance_data_generator', 'generate_and_store_data', 'scheduled__2024-12-02T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/finance_data_generator.py', '--cfg-path', '/tmp/tmptolyldmr']
[2024-12-03T15:04:44.348+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask generate_and_store_data
[2024-12-03T15:04:44.416+0000] {task_command.py:467} INFO - Running <TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [running]> on host 6e3bd31ba9a2
[2024-12-03T15:04:44.529+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='finance_data_generator' AIRFLOW_CTX_TASK_ID='generate_and_store_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-02T00:00:00+00:00'
[2024-12-03T15:04:44.530+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-03T15:04:44.531+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-03T15:04:44.531+0000] {logging_mixin.py:190} INFO - Current task name:generate_and_store_data state:running start_date:2024-12-03 15:04:44.298863+00:00
[2024-12-03T15:04:44.531+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator and current dag run status:running
[2024-12-03T15:04:44.532+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-03T15:05:13.643+0000] {logging_mixin.py:190} INFO - Transactions successfully stored in database
[2024-12-03T15:05:13.644+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-03T15:05:13.691+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-03T15:05:13.692+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=finance_data_generator, task_id=generate_and_store_data, run_id=scheduled__2024-12-02T00:00:00+00:00, execution_date=20241202T000000, start_date=20241203T150444, end_date=20241203T150513
[2024-12-03T15:05:13.762+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-03T15:05:13.763+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-03T15:05:13.764+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator queued_at:2024-12-03 15:04:38.898283+00:00
[2024-12-03T15:05:13.764+0000] {logging_mixin.py:190} INFO - Task hostname:6e3bd31ba9a2 operator:PythonOperator
[2024-12-03T15:05:13.831+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-03T15:05:13.896+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T15:05:13.902+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-03T15:11:01.900+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-03T15:11:01.924+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T15:11:01.936+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T15:11:01.937+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-03T15:11:01.961+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_and_store_data> on 2024-12-02 00:00:00+00:00
[2024-12-03T15:11:01.971+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=83) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-03T15:11:01.972+0000] {standard_task_runner.py:72} INFO - Started process 86 to run task
[2024-12-03T15:11:01.973+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'finance_data_generator', 'generate_and_store_data', 'scheduled__2024-12-02T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/finance_data_generator.py', '--cfg-path', '/tmp/tmpalpb03xl']
[2024-12-03T15:11:01.974+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask generate_and_store_data
[2024-12-03T15:11:02.042+0000] {task_command.py:467} INFO - Running <TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [running]> on host 9b8902cd5155
[2024-12-03T15:11:02.141+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='finance_data_generator' AIRFLOW_CTX_TASK_ID='generate_and_store_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-02T00:00:00+00:00'
[2024-12-03T15:11:02.143+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-03T15:11:02.144+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-03T15:11:02.144+0000] {logging_mixin.py:190} INFO - Current task name:generate_and_store_data state:running start_date:2024-12-03 15:11:01.924981+00:00
[2024-12-03T15:11:02.145+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator and current dag run status:running
[2024-12-03T15:11:02.145+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-03T15:14:49.423+0000] {logging_mixin.py:190} INFO - Transactions successfully stored in database
[2024-12-03T15:14:49.424+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-03T15:14:49.455+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-03T15:14:49.456+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=finance_data_generator, task_id=generate_and_store_data, run_id=scheduled__2024-12-02T00:00:00+00:00, execution_date=20241202T000000, start_date=20241203T151101, end_date=20241203T151449
[2024-12-03T15:14:49.479+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-03T15:14:49.479+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-03T15:14:49.480+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator queued_at:2024-12-03 15:10:56.579435+00:00
[2024-12-03T15:14:49.480+0000] {logging_mixin.py:190} INFO - Task hostname:9b8902cd5155 operator:PythonOperator
[2024-12-03T15:14:49.527+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-03T15:14:49.588+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T15:14:49.599+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-03T15:21:00.215+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-03T15:21:00.236+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T15:21:00.246+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T15:21:00.246+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-03T15:21:00.263+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_and_store_data> on 2024-12-02 00:00:00+00:00
[2024-12-03T15:21:00.273+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=74) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-03T15:21:00.275+0000] {standard_task_runner.py:72} INFO - Started process 86 to run task
[2024-12-03T15:21:00.276+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'finance_data_generator', 'generate_and_store_data', 'scheduled__2024-12-02T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/finance_data_generator.py', '--cfg-path', '/tmp/tmp34x6_z0j']
[2024-12-03T15:21:00.278+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask generate_and_store_data
[2024-12-03T15:21:00.349+0000] {task_command.py:467} INFO - Running <TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [running]> on host aba89591d242
[2024-12-03T15:21:00.470+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='finance_data_generator' AIRFLOW_CTX_TASK_ID='generate_and_store_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-02T00:00:00+00:00'
[2024-12-03T15:21:00.472+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-03T15:21:00.473+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-03T15:21:00.473+0000] {logging_mixin.py:190} INFO - Current task name:generate_and_store_data state:running start_date:2024-12-03 15:21:00.236573+00:00
[2024-12-03T15:21:00.474+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator and current dag run status:running
[2024-12-03T15:21:00.474+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-03T15:21:00.669+0000] {logging_mixin.py:190} INFO - Transactions successfully stored in database
[2024-12-03T15:21:00.669+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-03T15:21:00.687+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-03T15:21:00.688+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=finance_data_generator, task_id=generate_and_store_data, run_id=scheduled__2024-12-02T00:00:00+00:00, execution_date=20241202T000000, start_date=20241203T152100, end_date=20241203T152100
[2024-12-03T15:21:00.711+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-03T15:21:00.712+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-03T15:21:00.712+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator queued_at:2024-12-03 15:20:54.507598+00:00
[2024-12-03T15:21:00.712+0000] {logging_mixin.py:190} INFO - Task hostname:aba89591d242 operator:PythonOperator
[2024-12-03T15:21:00.732+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-03T15:21:00.759+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T15:21:00.765+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-03T15:49:28.938+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-03T15:49:28.970+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T15:49:28.984+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T15:49:28.985+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-03T15:49:29.005+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_and_store_data> on 2024-12-02 00:00:00+00:00
[2024-12-03T15:49:29.015+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=81) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-03T15:49:29.018+0000] {standard_task_runner.py:72} INFO - Started process 86 to run task
[2024-12-03T15:49:29.020+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'finance_data_generator', 'generate_and_store_data', 'scheduled__2024-12-02T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/finance_data_generator.py', '--cfg-path', '/tmp/tmpimltstzb']
[2024-12-03T15:49:29.022+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask generate_and_store_data
[2024-12-03T15:49:29.110+0000] {task_command.py:467} INFO - Running <TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [running]> on host bd8ab49cf491
[2024-12-03T15:49:29.263+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='finance_data_generator' AIRFLOW_CTX_TASK_ID='generate_and_store_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-02T00:00:00+00:00'
[2024-12-03T15:49:29.266+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-03T15:49:29.267+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-03T15:49:29.267+0000] {logging_mixin.py:190} INFO - Current task name:generate_and_store_data state:running start_date:2024-12-03 15:49:28.970704+00:00
[2024-12-03T15:49:29.268+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator and current dag run status:running
[2024-12-03T15:49:29.268+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-03T15:50:19.663+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-12-03T15:50:19.664+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-03T15:50:19.668+0000] {process_utils.py:132} INFO - Sending 15 to group 86. PIDs of all processes in the group: [86]
[2024-12-03T15:50:19.669+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 86
[2024-12-03T15:50:49.680+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-03T15:50:49.682+0000] {logging_mixin.py:190} INFO - Error storing transactions: Can't reconnect until invalid transaction is rolled back. (Background on this error at: https://sqlalche.me/e/14/8s2b)
[2024-12-03T15:50:49.683+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/finance_data_generator.py", line 23, in generate_and_store_data
    store_transactions_to_db(df, engine)
  File "/opt/airflow/dags/utils/db_operations.py", line 28, in store_transactions_to_db
    df.to_sql('transactions', engine, if_exists='replace', index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3008, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 787, in to_sql
    with pandasSQL_builder(con, schema=schema, need_transaction=True) as pandas_sql:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1585, in __exit__
    self.exit_stack.close()
  File "/usr/local/lib/python3.12/contextlib.py", line 618, in close
    self.__exit__(None, None, None)
  File "/usr/local/lib/python3.12/contextlib.py", line 610, in __exit__
    raise exc_details[1]
  File "/usr/local/lib/python3.12/contextlib.py", line 595, in __exit__
    if cb(*exc_details):
       ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/util.py", line 235, in __exit__
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/util.py", line 233, in __exit__
    self.commit()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2469, in commit
    self._do_commit()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2659, in _do_commit
    self._connection_commit_impl()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2630, in _connection_commit_impl
    self.connection._commit_impl()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1096, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2138, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1094, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
                                  ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 537, in connection
    return self._revalidate_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 650, in _revalidate_connection
    self._invalid_transaction()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 622, in _invalid_transaction
    raise exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: Can't reconnect until invalid transaction is rolled back. (Background on this error at: https://sqlalche.me/e/14/8s2b)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/finance_data_generator.py", line 25, in generate_and_store_data
    raise AirflowFailException(f"Data generation or storage failed: {e}")
airflow.exceptions.AirflowFailException: Data generation or storage failed: Can't reconnect until invalid transaction is rolled back. (Background on this error at: https://sqlalche.me/e/14/8s2b)
[2024-12-03T15:50:49.744+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-03T15:50:49.746+0000] {logging_mixin.py:190} INFO - Task start:2024-12-03 15:49:28.970704+00:00 end:2024-12-03 15:50:49.743365+00:00 duration:80.772661
[2024-12-03T15:50:49.747+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): generate_and_store_data> dag:<DAG: finance_data_generator> dagrun:<DagRun finance_data_generator @ 2024-12-02 00:00:00+00:00: scheduled__2024-12-02T00:00:00+00:00, state:running, queued_at: 2024-12-03 15:49:20.034759+00:00. externally triggered: False>
[2024-12-03T15:50:49.747+0000] {logging_mixin.py:190} INFO - Failure caused by Data generation or storage failed: Can't reconnect until invalid transaction is rolled back. (Background on this error at: https://sqlalche.me/e/14/8s2b)
[2024-12-03T15:50:49.748+0000] {taskinstance.py:1225} INFO - Immediate failure requested. Marking task as FAILED. dag_id=finance_data_generator, task_id=generate_and_store_data, run_id=scheduled__2024-12-02T00:00:00+00:00, execution_date=20241202T000000, start_date=20241203T154928, end_date=20241203T155049
[2024-12-03T15:50:49.828+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-03T15:50:49.829+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4 for task generate_and_store_data (Data generation or storage failed: Can't reconnect until invalid transaction is rolled back. (Background on this error at: https://sqlalche.me/e/14/8s2b); 86)
Traceback (most recent call last):
  File "/opt/airflow/dags/finance_data_generator.py", line 23, in generate_and_store_data
    store_transactions_to_db(df, engine)
  File "/opt/airflow/dags/utils/db_operations.py", line 28, in store_transactions_to_db
    df.to_sql('transactions', engine, if_exists='replace', index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3008, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 787, in to_sql
    with pandasSQL_builder(con, schema=schema, need_transaction=True) as pandas_sql:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1585, in __exit__
    self.exit_stack.close()
  File "/usr/local/lib/python3.12/contextlib.py", line 618, in close
    self.__exit__(None, None, None)
  File "/usr/local/lib/python3.12/contextlib.py", line 610, in __exit__
    raise exc_details[1]
  File "/usr/local/lib/python3.12/contextlib.py", line 595, in __exit__
    if cb(*exc_details):
       ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/util.py", line 235, in __exit__
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/util.py", line 233, in __exit__
    self.commit()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2469, in commit
    self._do_commit()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2659, in _do_commit
    self._connection_commit_impl()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2630, in _connection_commit_impl
    self.connection._commit_impl()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1096, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2138, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1094, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
                                  ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 537, in connection
    return self._revalidate_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 650, in _revalidate_connection
    self._invalid_transaction()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 622, in _invalid_transaction
    raise exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: Can't reconnect until invalid transaction is rolled back. (Background on this error at: https://sqlalche.me/e/14/8s2b)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/finance_data_generator.py", line 25, in generate_and_store_data
    raise AirflowFailException(f"Data generation or storage failed: {e}")
airflow.exceptions.AirflowFailException: Data generation or storage failed: Can't reconnect until invalid transaction is rolled back. (Background on this error at: https://sqlalche.me/e/14/8s2b)
[2024-12-03T15:50:49.923+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=86, status='terminated', exitcode=1, started='15:49:28') (86) terminated with exit code 1
[2024-12-03T15:56:52.811+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-03T15:56:52.841+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T15:56:52.854+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T15:56:52.855+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-03T15:56:52.885+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_and_store_data> on 2024-12-02 00:00:00+00:00
[2024-12-03T15:56:52.897+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=75) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-03T15:56:52.899+0000] {standard_task_runner.py:72} INFO - Started process 87 to run task
[2024-12-03T15:56:52.901+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'finance_data_generator', 'generate_and_store_data', 'scheduled__2024-12-02T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/finance_data_generator.py', '--cfg-path', '/tmp/tmpd5nszu7q']
[2024-12-03T15:56:52.903+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask generate_and_store_data
[2024-12-03T15:56:52.988+0000] {task_command.py:467} INFO - Running <TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [running]> on host 42f37546b51b
[2024-12-03T15:56:53.148+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='finance_data_generator' AIRFLOW_CTX_TASK_ID='generate_and_store_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-02T00:00:00+00:00'
[2024-12-03T15:56:53.150+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-03T15:56:53.151+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-03T15:56:53.151+0000] {logging_mixin.py:190} INFO - Current task name:generate_and_store_data state:running start_date:2024-12-03 15:56:52.841786+00:00
[2024-12-03T15:56:53.152+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator and current dag run status:running
[2024-12-03T15:56:53.152+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-03T15:56:53.250+0000] {logging_mixin.py:190} INFO - Transactions successfully stored in database
[2024-12-03T15:56:53.250+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-03T15:56:53.268+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-03T15:56:53.269+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=finance_data_generator, task_id=generate_and_store_data, run_id=scheduled__2024-12-02T00:00:00+00:00, execution_date=20241202T000000, start_date=20241203T155652, end_date=20241203T155653
[2024-12-03T15:56:53.285+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-03T15:56:53.285+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-03T15:56:53.286+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator queued_at:2024-12-03 15:56:44.486472+00:00
[2024-12-03T15:56:53.286+0000] {logging_mixin.py:190} INFO - Task hostname:42f37546b51b operator:PythonOperator
[2024-12-03T15:56:53.315+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-03T15:56:53.353+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T15:56:53.356+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-03T16:34:57.576+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-03T16:34:57.609+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T16:34:57.625+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T16:34:57.626+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-03T16:34:57.649+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_and_store_data> on 2024-12-02 00:00:00+00:00
[2024-12-03T16:34:57.660+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=80) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-03T16:34:57.661+0000] {standard_task_runner.py:72} INFO - Started process 92 to run task
[2024-12-03T16:34:57.663+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'finance_data_generator', 'generate_and_store_data', 'scheduled__2024-12-02T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/finance_data_generator.py', '--cfg-path', '/tmp/tmpvbc_0_l_']
[2024-12-03T16:34:57.665+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask generate_and_store_data
[2024-12-03T16:34:57.758+0000] {task_command.py:467} INFO - Running <TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [running]> on host baccf4d99c3e
[2024-12-03T16:34:57.901+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='finance_data_generator' AIRFLOW_CTX_TASK_ID='generate_and_store_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-02T00:00:00+00:00'
[2024-12-03T16:34:57.903+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-03T16:34:57.904+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-03T16:34:57.905+0000] {logging_mixin.py:190} INFO - Current task name:generate_and_store_data state:running start_date:2024-12-03 16:34:57.609747+00:00
[2024-12-03T16:34:57.905+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator and current dag run status:running
[2024-12-03T16:34:57.906+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-03T16:34:58.038+0000] {logging_mixin.py:190} INFO - Transactions successfully stored in database
[2024-12-03T16:34:58.039+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-03T16:34:58.065+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-03T16:34:58.066+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=finance_data_generator, task_id=generate_and_store_data, run_id=scheduled__2024-12-02T00:00:00+00:00, execution_date=20241202T000000, start_date=20241203T163457, end_date=20241203T163458
[2024-12-03T16:34:58.087+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-03T16:34:58.087+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-03T16:34:58.088+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator queued_at:2024-12-03 16:34:48.935174+00:00
[2024-12-03T16:34:58.088+0000] {logging_mixin.py:190} INFO - Task hostname:baccf4d99c3e operator:PythonOperator
[2024-12-03T16:34:58.117+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-03T16:34:58.145+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T16:34:58.147+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-03T16:52:11.210+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-03T16:52:11.246+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T16:52:11.259+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T16:52:11.260+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-03T16:52:11.290+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_and_store_data> on 2024-12-02 00:00:00+00:00
[2024-12-03T16:52:11.303+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=89) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-03T16:52:11.305+0000] {standard_task_runner.py:72} INFO - Started process 93 to run task
[2024-12-03T16:52:11.305+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'finance_data_generator', 'generate_and_store_data', 'scheduled__2024-12-02T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/finance_data_generator.py', '--cfg-path', '/tmp/tmp078wejxe']
[2024-12-03T16:52:11.307+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask generate_and_store_data
[2024-12-03T16:52:11.398+0000] {task_command.py:467} INFO - Running <TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [running]> on host cfcad96c649a
[2024-12-03T16:52:11.554+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='finance_data_generator' AIRFLOW_CTX_TASK_ID='generate_and_store_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-02T00:00:00+00:00'
[2024-12-03T16:52:11.556+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-03T16:52:11.557+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-03T16:52:11.558+0000] {logging_mixin.py:190} INFO - Current task name:generate_and_store_data state:running start_date:2024-12-03 16:52:11.247131+00:00
[2024-12-03T16:52:11.558+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator and current dag run status:running
[2024-12-03T16:52:11.558+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-03T16:52:11.666+0000] {logging_mixin.py:190} INFO - Transactions successfully stored in database
[2024-12-03T16:52:11.667+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-03T16:52:11.689+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-03T16:52:11.689+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=finance_data_generator, task_id=generate_and_store_data, run_id=scheduled__2024-12-02T00:00:00+00:00, execution_date=20241202T000000, start_date=20241203T165211, end_date=20241203T165211
[2024-12-03T16:52:11.709+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-03T16:52:11.710+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-03T16:52:11.711+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator queued_at:2024-12-03 16:52:03.305101+00:00
[2024-12-03T16:52:11.711+0000] {logging_mixin.py:190} INFO - Task hostname:cfcad96c649a operator:PythonOperator
[2024-12-03T16:52:11.762+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-03T16:52:11.792+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T16:52:11.795+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-03T17:02:13.478+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-03T17:02:13.514+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T17:02:13.529+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T17:02:13.530+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-03T17:02:13.554+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_and_store_data> on 2024-12-02 00:00:00+00:00
[2024-12-03T17:02:13.567+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=82) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-03T17:02:13.569+0000] {standard_task_runner.py:72} INFO - Started process 87 to run task
[2024-12-03T17:02:13.570+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'finance_data_generator', 'generate_and_store_data', 'scheduled__2024-12-02T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/finance_data_generator.py', '--cfg-path', '/tmp/tmpo9wrhfg6']
[2024-12-03T17:02:13.571+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask generate_and_store_data
[2024-12-03T17:02:13.672+0000] {task_command.py:467} INFO - Running <TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [running]> on host cc25cf211a81
[2024-12-03T17:02:13.829+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='finance_data_generator' AIRFLOW_CTX_TASK_ID='generate_and_store_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-02T00:00:00+00:00'
[2024-12-03T17:02:13.831+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-03T17:02:13.832+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-03T17:02:13.832+0000] {logging_mixin.py:190} INFO - Current task name:generate_and_store_data state:running start_date:2024-12-03 17:02:13.515117+00:00
[2024-12-03T17:02:13.833+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator and current dag run status:running
[2024-12-03T17:02:13.833+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-03T17:02:13.970+0000] {logging_mixin.py:190} INFO - Transactions successfully stored in database
[2024-12-03T17:02:13.971+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-03T17:02:13.995+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-03T17:02:13.996+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=finance_data_generator, task_id=generate_and_store_data, run_id=scheduled__2024-12-02T00:00:00+00:00, execution_date=20241202T000000, start_date=20241203T170213, end_date=20241203T170213
[2024-12-03T17:02:14.018+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-03T17:02:14.019+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-03T17:02:14.019+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator queued_at:2024-12-03 17:02:05.246569+00:00
[2024-12-03T17:02:14.020+0000] {logging_mixin.py:190} INFO - Task hostname:cc25cf211a81 operator:PythonOperator
[2024-12-03T17:02:14.071+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-03T17:02:14.101+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T17:02:14.103+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-03T17:38:08.737+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-03T17:38:08.770+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T17:38:08.784+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T17:38:08.784+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-03T17:38:08.819+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_and_store_data> on 2024-12-02 00:00:00+00:00
[2024-12-03T17:38:08.830+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=75) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-03T17:38:08.831+0000] {standard_task_runner.py:72} INFO - Started process 78 to run task
[2024-12-03T17:38:08.833+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'finance_data_generator', 'generate_and_store_data', 'scheduled__2024-12-02T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/finance_data_generator.py', '--cfg-path', '/tmp/tmpe7tvdbsm']
[2024-12-03T17:38:08.834+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask generate_and_store_data
[2024-12-03T17:38:08.929+0000] {task_command.py:467} INFO - Running <TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [running]> on host c1f20a170a3c
[2024-12-03T17:38:09.080+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='finance_data_generator' AIRFLOW_CTX_TASK_ID='generate_and_store_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-02T00:00:00+00:00'
[2024-12-03T17:38:09.082+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-03T17:38:09.082+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-03T17:38:09.083+0000] {logging_mixin.py:190} INFO - Current task name:generate_and_store_data state:running start_date:2024-12-03 17:38:08.771052+00:00
[2024-12-03T17:38:09.083+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator and current dag run status:running
[2024-12-03T17:38:09.084+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-03T17:38:09.196+0000] {logging_mixin.py:190} INFO - Transactions successfully stored in database
[2024-12-03T17:38:09.197+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-03T17:38:09.216+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-03T17:38:09.217+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=finance_data_generator, task_id=generate_and_store_data, run_id=scheduled__2024-12-02T00:00:00+00:00, execution_date=20241202T000000, start_date=20241203T173808, end_date=20241203T173809
[2024-12-03T17:38:09.238+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-03T17:38:09.239+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-03T17:38:09.239+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator queued_at:2024-12-03 17:37:59.388741+00:00
[2024-12-03T17:38:09.239+0000] {logging_mixin.py:190} INFO - Task hostname:c1f20a170a3c operator:PythonOperator
[2024-12-03T17:38:09.288+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-03T17:38:09.335+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T17:38:09.338+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-03T17:58:47.007+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-03T17:58:47.036+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T17:58:47.048+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T17:58:47.049+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-03T17:58:47.073+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_and_store_data> on 2024-12-02 00:00:00+00:00
[2024-12-03T17:58:47.081+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=73) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-03T17:58:47.082+0000] {standard_task_runner.py:72} INFO - Started process 77 to run task
[2024-12-03T17:58:47.084+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'finance_data_generator', 'generate_and_store_data', 'scheduled__2024-12-02T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/finance_data_generator.py', '--cfg-path', '/tmp/tmpxvq77p6t']
[2024-12-03T17:58:47.085+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask generate_and_store_data
[2024-12-03T17:58:47.181+0000] {task_command.py:467} INFO - Running <TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [running]> on host c4ca343f6ce9
[2024-12-03T17:58:47.350+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='finance_data_generator' AIRFLOW_CTX_TASK_ID='generate_and_store_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-02T00:00:00+00:00'
[2024-12-03T17:58:47.352+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-03T17:58:47.352+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-03T17:58:47.353+0000] {logging_mixin.py:190} INFO - Current task name:generate_and_store_data state:running start_date:2024-12-03 17:58:47.036501+00:00
[2024-12-03T17:58:47.353+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator and current dag run status:running
[2024-12-03T17:58:47.354+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-03T17:58:47.698+0000] {logging_mixin.py:190} INFO - Transactions successfully stored in database
[2024-12-03T17:58:47.699+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-03T17:58:47.721+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-03T17:58:47.722+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=finance_data_generator, task_id=generate_and_store_data, run_id=scheduled__2024-12-02T00:00:00+00:00, execution_date=20241202T000000, start_date=20241203T175847, end_date=20241203T175847
[2024-12-03T17:58:47.753+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-03T17:58:47.754+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-03T17:58:47.755+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator queued_at:2024-12-03 17:58:37.619052+00:00
[2024-12-03T17:58:47.756+0000] {logging_mixin.py:190} INFO - Task hostname:c4ca343f6ce9 operator:PythonOperator
[2024-12-03T17:58:47.779+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-03T17:58:47.813+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T17:58:47.819+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-03T18:08:07.323+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-03T18:08:07.350+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T18:08:07.365+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T18:08:07.366+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-03T18:08:07.395+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_and_store_data> on 2024-12-02 00:00:00+00:00
[2024-12-03T18:08:07.406+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=75) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-03T18:08:07.408+0000] {standard_task_runner.py:72} INFO - Started process 79 to run task
[2024-12-03T18:08:07.409+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'finance_data_generator', 'generate_and_store_data', 'scheduled__2024-12-02T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/finance_data_generator.py', '--cfg-path', '/tmp/tmpsyu8v_z0']
[2024-12-03T18:08:07.411+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask generate_and_store_data
[2024-12-03T18:08:07.491+0000] {task_command.py:467} INFO - Running <TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [running]> on host e0b5493226e4
[2024-12-03T18:08:07.665+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='finance_data_generator' AIRFLOW_CTX_TASK_ID='generate_and_store_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-02T00:00:00+00:00'
[2024-12-03T18:08:07.667+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-03T18:08:07.668+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-03T18:08:07.669+0000] {logging_mixin.py:190} INFO - Current task name:generate_and_store_data state:running start_date:2024-12-03 18:08:07.351525+00:00
[2024-12-03T18:08:07.669+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator and current dag run status:running
[2024-12-03T18:08:07.669+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-03T18:08:38.269+0000] {logging_mixin.py:190} INFO - Transactions successfully stored in database
[2024-12-03T18:08:38.270+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-03T18:08:38.299+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-03T18:08:38.301+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=finance_data_generator, task_id=generate_and_store_data, run_id=scheduled__2024-12-02T00:00:00+00:00, execution_date=20241202T000000, start_date=20241203T180807, end_date=20241203T180838
[2024-12-03T18:08:38.344+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-03T18:08:38.345+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-03T18:08:38.346+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator queued_at:2024-12-03 18:07:57.743243+00:00
[2024-12-03T18:08:38.347+0000] {logging_mixin.py:190} INFO - Task hostname:e0b5493226e4 operator:PythonOperator
[2024-12-03T18:08:38.416+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-03T18:08:38.459+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T18:08:38.466+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-03T18:11:15.856+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-03T18:11:15.888+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T18:11:15.906+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T18:11:15.907+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-03T18:11:15.943+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_and_store_data> on 2024-12-02 00:00:00+00:00
[2024-12-03T18:11:15.955+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=75) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-03T18:11:15.956+0000] {standard_task_runner.py:72} INFO - Started process 87 to run task
[2024-12-03T18:11:15.959+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'finance_data_generator', 'generate_and_store_data', 'scheduled__2024-12-02T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/finance_data_generator.py', '--cfg-path', '/tmp/tmpyrulx6n3']
[2024-12-03T18:11:15.961+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask generate_and_store_data
[2024-12-03T18:11:16.052+0000] {task_command.py:467} INFO - Running <TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [running]> on host d8011871c704
[2024-12-03T18:11:16.237+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='finance_data_generator' AIRFLOW_CTX_TASK_ID='generate_and_store_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-02T00:00:00+00:00'
[2024-12-03T18:11:16.239+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-03T18:11:16.239+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-03T18:11:16.240+0000] {logging_mixin.py:190} INFO - Current task name:generate_and_store_data state:running start_date:2024-12-03 18:11:15.888779+00:00
[2024-12-03T18:11:16.240+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator and current dag run status:running
[2024-12-03T18:11:16.241+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-03T18:11:16.355+0000] {logging_mixin.py:190} INFO - Transactions successfully stored in database
[2024-12-03T18:11:16.356+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-03T18:11:16.379+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-03T18:11:16.380+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=finance_data_generator, task_id=generate_and_store_data, run_id=scheduled__2024-12-02T00:00:00+00:00, execution_date=20241202T000000, start_date=20241203T181115, end_date=20241203T181116
[2024-12-03T18:11:16.399+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-03T18:11:16.400+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-03T18:11:16.400+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator queued_at:2024-12-03 18:11:06.000785+00:00
[2024-12-03T18:11:16.401+0000] {logging_mixin.py:190} INFO - Task hostname:d8011871c704 operator:PythonOperator
[2024-12-03T18:11:16.455+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-03T18:11:16.489+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T18:11:16.492+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-03T18:25:05.825+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-03T18:25:05.858+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T18:25:05.870+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T18:25:05.871+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-03T18:25:05.890+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_and_store_data> on 2024-12-02 00:00:00+00:00
[2024-12-03T18:25:05.901+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=82) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-03T18:25:05.902+0000] {standard_task_runner.py:72} INFO - Started process 93 to run task
[2024-12-03T18:25:05.904+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'finance_data_generator', 'generate_and_store_data', 'scheduled__2024-12-02T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/finance_data_generator.py', '--cfg-path', '/tmp/tmpr520dbel']
[2024-12-03T18:25:05.906+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask generate_and_store_data
[2024-12-03T18:25:06.000+0000] {task_command.py:467} INFO - Running <TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-02T00:00:00+00:00 [running]> on host fad9b829ed30
[2024-12-03T18:25:06.164+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='finance_data_generator' AIRFLOW_CTX_TASK_ID='generate_and_store_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-02T00:00:00+00:00'
[2024-12-03T18:25:06.166+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-03T18:25:06.166+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-03T18:25:06.167+0000] {logging_mixin.py:190} INFO - Current task name:generate_and_store_data state:running start_date:2024-12-03 18:25:05.859305+00:00
[2024-12-03T18:25:06.168+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator and current dag run status:running
[2024-12-03T18:25:06.168+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-03T18:25:06.280+0000] {logging_mixin.py:190} INFO - Transactions successfully stored in database
[2024-12-03T18:25:06.281+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-03T18:25:06.302+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-03T18:25:06.303+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=finance_data_generator, task_id=generate_and_store_data, run_id=scheduled__2024-12-02T00:00:00+00:00, execution_date=20241202T000000, start_date=20241203T182505, end_date=20241203T182506
[2024-12-03T18:25:06.323+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-03T18:25:06.324+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-03T18:25:06.325+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator queued_at:2024-12-03 18:24:58.208114+00:00
[2024-12-03T18:25:06.325+0000] {logging_mixin.py:190} INFO - Task hostname:fad9b829ed30 operator:PythonOperator
[2024-12-03T18:25:06.358+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-03T18:25:06.389+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T18:25:06.392+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
